### ISSUE TITLE
Clean UP & Dockerization eos4u6p

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4u6p#1]

**Comment by HellenNamulinda** [comment]
The model couldn't work initially, as the Mode Test on push [failed](https://github.com/ersilia-os/eos4u6p/actions/runs/5424646963/jobs/9864302369),  This was because of [package conflicts](https://github.com/ersilia-os/eos4u6p/actions/runs/5424646963/jobs/9864302369#step:10:607) for rkdit 2019.03 and syntax errors in [model code](https://github.com/ersilia-os/eos4u6p/actions/runs/5424646963/jobs/9864302369#step:10:1291).
```
If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /home/runner/eos/current.log
/home/runner/eos/repository/eos4u6p/20230630162158_B6876B/eos4u6p/artifacts/framework/predict.py: line 4: from: command not found
/home/runner/eos/repository/eos4u6p/20230630162158_B6876B/eos4u6p/artifacts/framework/predict.py: line 6: syntax error near unexpected token `('
/home/runner/eos/repository/eos4u6p/20230630162158_B6876B/eos4u6p/artifacts/framework/predict.py: line 6: `DATASETS = ["{0}{1}".format(x, y) for x in "ABCDE" for y in "12345"]'
```
Checking the original author's [repository](https://gitlabsbnb.irbbarcelona.org/packages/signaturizer/-/blob/master/requirements.txt), they don't specify the rdkit version and they install it using rdkit, which will install the latest. So we will modify the package requirements to those of the authors.

**Comment by HellenNamulinda** [comment]
Hi @GemmaTuron, 
I made the changes and created a [PR](https://github.com/ersilia-os/eos4u6p/pull/2)
I tested the model locally using both run.sh and --repo_path. It works well.
```
(ersilia) hellenah@hellenah-elitebook:~$ ersilia -v fetch eos4u6p --repo_path Outreachy/eos4u6p > eos4u6p_fetch_repo.log 2>&1
(ersilia) hellenah@hellenah-elitebook:~$ ersilia serve eos4u6p
🚀 Serving model eos4u6p: cc-signaturizer

   URL: http://127.0.0.1:56655
   PID: 53788
   SRV: conda

👉 To run model:
   - run

💁 Information:
   - info
(ersilia) hellenah@hellenah-elitebook:~$ ersilia run -i "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
{
    "input": {
        "key": "MCGSCOLBFJQGHM-SCZZXKLOSA-N",
        "input": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1",
        "text": "Nc1nc(NC2CC2)c3ncn([C@@H]4C[C@H](CO)C=C4)c3n1"
    },
    "output": {
        "A1": [
            0.08105449378490448,
            0.09470740705728531,
            -0.06483583897352219,
            -0.0708528608083725,
            -0.09902401268482208,
            0.08934140205383301,
            0.09902401268482208,
            0.09590023010969162,
            0.04880361258983612,
            0.09810621291399002,
            -0.04856538400053978,
...
```
[eos4u6p_fetch_repo.log](https://github.com/ersilia-os/eos4u6p/files/12009366/eos4u6p_fetch_repo.log)
Test file: [eml_50.csv](https://github.com/ersilia-os/eos4u6p/files/12009376/eml_50.csv)
Output: [eos4u6p_eml_cli_output.csv](https://github.com/ersilia-os/eos4u6p/files/12009365/eos4u6p_eml_cli_output.csv)

**Comment by GemmaTuron** [comment]
this model is completed
